-- =============================================================================
-- ACTION by Depth Analytics — reference data seed
--
-- Seeds the `teams` table for all four supported leagues (NFL, NBA, MLB, NHL).
-- Games are NOT seeded here — they are upserted on demand from whichever
-- SportsDataProvider is active (see src/lib/sports-data) the first time a
-- user searches for and selects a game. This keeps `games` a live mirror of
-- the provider instead of a second source of truth that can drift.
--
-- Safe to re-run: uses ON CONFLICT DO NOTHING against the (league, abbreviation)
-- unique constraint.
-- =============================================================================

insert into teams (league, city, name, abbreviation, primary_color) values
-- ---------------------------------------------------------------- NFL (32) --
('NFL','Buffalo','Bills','BUF','#00338D'),
('NFL','Miami','Dolphins','MIA','#008E97'),
('NFL','New England','Patriots','NE','#002244'),
('NFL','New York','Jets','NYJ','#125740'),
('NFL','Baltimore','Ravens','BAL','#241773'),
('NFL','Cincinnati','Bengals','CIN','#FB4F14'),
('NFL','Cleveland','Browns','CLE','#311D00'),
('NFL','Pittsburgh','Steelers','PIT','#FFB612'),
('NFL','Houston','Texans','HOU','#03202F'),
('NFL','Indianapolis','Colts','IND','#002C5F'),
('NFL','Jacksonville','Jaguars','JAX','#101820'),
('NFL','Tennessee','Titans','TEN','#0C2340'),
('NFL','Denver','Broncos','DEN','#FB4F14'),
('NFL','Kansas City','Chiefs','KC','#E31837'),
('NFL','Las Vegas','Raiders','LV','#000000'),
('NFL','Los Angeles','Chargers','LAC','#0080C6'),
('NFL','Dallas','Cowboys','DAL','#041E42'),
('NFL','New York','Giants','NYG','#0B2265'),
('NFL','Philadelphia','Eagles','PHI','#004C54'),
('NFL','Washington','Commanders','WAS','#5A1414'),
('NFL','Chicago','Bears','CHI','#0B162A'),
('NFL','Detroit','Lions','DET','#0076B6'),
('NFL','Green Bay','Packers','GB','#203731'),
('NFL','Minnesota','Vikings','MIN','#4F2683'),
('NFL','Atlanta','Falcons','ATL','#A71930'),
('NFL','Carolina','Panthers','CAR','#0085CA'),
('NFL','New Orleans','Saints','NO','#D3BC8D'),
('NFL','Tampa Bay','Buccaneers','TB','#D50A0A'),
('NFL','Arizona','Cardinals','ARI','#97233F'),
('NFL','Los Angeles','Rams','LAR','#003594'),
('NFL','San Francisco','49ers','SF','#AA0000'),
('NFL','Seattle','Seahawks','SEA','#002244'),
-- ---------------------------------------------------------------- NBA (30) --
('NBA','Boston','Celtics','BOS','#007A33'),
('NBA','Brooklyn','Nets','BKN','#000000'),
('NBA','New York','Knicks','NYK','#006BB6'),
('NBA','Philadelphia','76ers','PHI','#006BB6'),
('NBA','Toronto','Raptors','TOR','#CE1141'),
('NBA','Chicago','Bulls','CHI','#CE1141'),
('NBA','Cleveland','Cavaliers','CLE','#6F263D'),
('NBA','Detroit','Pistons','DET','#C8102E'),
('NBA','Indiana','Pacers','IND','#002D62'),
('NBA','Milwaukee','Bucks','MIL','#00471B'),
('NBA','Atlanta','Hawks','ATL','#E03A3E'),
('NBA','Charlotte','Hornets','CHA','#1D1160'),
('NBA','Miami','Heat','MIA','#98002E'),
('NBA','Orlando','Magic','ORL','#0077C0'),
('NBA','Washington','Wizards','WAS','#002B5C'),
('NBA','Denver','Nuggets','DEN','#0E2240'),
('NBA','Minnesota','Timberwolves','MIN','#0C2340'),
('NBA','Oklahoma City','Thunder','OKC','#007AC1'),
('NBA','Portland','Trail Blazers','POR','#E03A3E'),
('NBA','Utah','Jazz','UTA','#002B5C'),
('NBA','Golden State','Warriors','GSW','#1D428A'),
('NBA','LA','Clippers','LAC','#C8102E'),
('NBA','Los Angeles','Lakers','LAL','#552583'),
('NBA','Phoenix','Suns','PHX','#1D1160'),
('NBA','Sacramento','Kings','SAC','#5A2D81'),
('NBA','Dallas','Mavericks','DAL','#00538C'),
('NBA','Houston','Rockets','HOU','#CE1141'),
('NBA','Memphis','Grizzlies','MEM','#5D76A9'),
('NBA','New Orleans','Pelicans','NOP','#0C2340'),
('NBA','San Antonio','Spurs','SAS','#C4CED4'),
-- ---------------------------------------------------------------- MLB (30) --
('MLB','Baltimore','Orioles','BAL','#DF4601'),
('MLB','Boston','Red Sox','BOS','#BD3039'),
('MLB','New York','Yankees','NYY','#0C2340'),
('MLB','Tampa Bay','Rays','TB','#092C5C'),
('MLB','Toronto','Blue Jays','TOR','#134A8E'),
('MLB','Chicago','White Sox','CWS','#27251F'),
('MLB','Cleveland','Guardians','CLE','#00385D'),
('MLB','Detroit','Tigers','DET','#0C2340'),
('MLB','Kansas City','Royals','KC','#004687'),
('MLB','Minnesota','Twins','MIN','#002B5C'),
('MLB','Houston','Astros','HOU','#EB6E1F'),
('MLB','Los Angeles','Angels','LAA','#BA0021'),
('MLB','Oakland','Athletics','OAK','#003831'),
('MLB','Seattle','Mariners','SEA','#0C2C56'),
('MLB','Texas','Rangers','TEX','#003278'),
('MLB','Atlanta','Braves','ATL','#CE1141'),
('MLB','Miami','Marlins','MIA','#00A3E0'),
('MLB','New York','Mets','NYM','#002D72'),
('MLB','Philadelphia','Phillies','PHI','#E81828'),
('MLB','Washington','Nationals','WSH','#AB0003'),
('MLB','Chicago','Cubs','CHC','#0E3386'),
('MLB','Cincinnati','Reds','CIN','#C6011F'),
('MLB','Milwaukee','Brewers','MIL','#12284B'),
('MLB','Pittsburgh','Pirates','PIT','#27251F'),
('MLB','St. Louis','Cardinals','STL','#C41E3A'),
('MLB','Arizona','Diamondbacks','ARI','#A71930'),
('MLB','Colorado','Rockies','COL','#333366'),
('MLB','Los Angeles','Dodgers','LAD','#005A9C'),
('MLB','San Diego','Padres','SD','#2F241D'),
('MLB','San Francisco','Giants','SF','#FD5A1E'),
-- ---------------------------------------------------------------- NHL (32) --
('NHL','Boston','Bruins','BOS','#FFB81C'),
('NHL','Buffalo','Sabres','BUF','#002654'),
('NHL','Detroit','Red Wings','DET','#CE1126'),
('NHL','Florida','Panthers','FLA','#041E42'),
('NHL','Montreal','Canadiens','MTL','#AF1E2D'),
('NHL','Ottawa','Senators','OTT','#C52032'),
('NHL','Tampa Bay','Lightning','TBL','#002868'),
('NHL','Toronto','Maple Leafs','TOR','#00205B'),
('NHL','Carolina','Hurricanes','CAR','#CC0000'),
('NHL','Columbus','Blue Jackets','CBJ','#002654'),
('NHL','New Jersey','Devils','NJD','#CE1126'),
('NHL','New York','Islanders','NYI','#00539B'),
('NHL','New York','Rangers','NYR','#0038A8'),
('NHL','Philadelphia','Flyers','PHI','#F74902'),
('NHL','Pittsburgh','Penguins','PIT','#FCB514'),
('NHL','Washington','Capitals','WSH','#041E42'),
('NHL','Chicago','Blackhawks','CHI','#CF0A2C'),
('NHL','Colorado','Avalanche','COL','#6F263D'),
('NHL','Dallas','Stars','DAL','#006847'),
('NHL','Minnesota','Wild','MIN','#154734'),
('NHL','Nashville','Predators','NSH','#FFB81C'),
('NHL','St. Louis','Blues','STL','#002F87'),
('NHL','Utah','Hockey Club','UTA','#71AFE5'),
('NHL','Winnipeg','Jets','WPG','#041E42'),
('NHL','Anaheim','Ducks','ANA','#F47A38'),
('NHL','Calgary','Flames','CGY','#C8102E'),
('NHL','Edmonton','Oilers','EDM','#041E42'),
('NHL','Los Angeles','Kings','LAK','#111111'),
('NHL','San Jose','Sharks','SJS','#006D75'),
('NHL','Seattle','Kraken','SEA','#001628'),
('NHL','Vancouver','Canucks','VAN','#00205B'),
('NHL','Vegas','Golden Knights','VGK','#B4975A')
on conflict (league, abbreviation) do nothing;
